; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "wxTED"
#define MyAppVersion "1.62"
#define MyAppPublisher "Peter Kwan"
#define MyAppURL "github.com/peterkvt80/wxted"
#define MyAppExeName "wxTED.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BF8D5847-6816-45D9-AB36-99F50155DCE4}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName=wxTED Teletext Editor
AllowNoIcons=yes
OutputDir=E:\dev\wxTED-GitHub\wxted\bin\Release
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes
VersionInfoVersion=1.62
ChangesAssociations = yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\wxTED.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\BBC100.tti"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\wxtedsplash.tti"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\manual.pdf"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\sample pages\*"; DestDir: "{app}\samples"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\Templates\*.tti"; DestDir: "{app}\Templates"; Flags: ignoreversion
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\teletext2.ttf"; DestDir: "{fonts}"; FontInstall: "teletext2"; Flags: onlyifdoesntexist uninsneveruninstall
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\Manual"; Filename: "{app}\manual.pdf"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
Root: "HKCR"; Subkey: ".tti";  ValueType: string; ValueData: "{#MyAppName}"; Flags: uninsdeletevalue
Root: "HKCR"; Subkey: ".ttix"; ValueType: string; ValueData: "{#MyAppName}"; Flags: uninsdeletevalue
Root: "HKCR"; Subkey: "{#MyAppName}"; ValueType: string; ValueData: "Program {#MyAppName}"; Flags: uninsdeletevalue; ValueName: ""
Root: "HKCR"; Subkey: "{#MyAppName}\DefaultIcon"; ValueType: string; ValueData: "{app}\{#MyAppExeName},0"; ValueName: ""
Root: "HKCR"; Subkey: "{#MyAppName}\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; ValueName: ""
