; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "wxTED"
#define MyAppVersion "1.63"
#define MyAppPublisher "Peter Kwan"
#define MyAppURL "github.com/peterkvt80/wxted"
#define MyAppExeName "wxTED.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{BF8D5847-6816-45D9-AB36-99F50155DCE4}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName=wxTED Teletext Editor
AllowNoIcons=yes
OutputDir=E:\dev\wxTED-GitHub\wxted\bin\Release
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes
VersionInfoVersion=1.63
; Ensure this is set to yes so the shell updates when the thumbnailer is added
ChangesAssociations=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Components]
Name: "wxTED"; Description: "wxTED Editor (Required)"; Types: full compact custom; Flags: fixed
Name: "thumbnails"; Description: "TTI Thumbnail Provider (Show previews in Explorer)"; Types: full

[Files]
; Existing files linked to 'main'
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\wxTED.exe"; DestDir: "{app}"; Flags: ignoreversion; Components: wxTED
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\BBC100.tti"; DestDir: "{app}"; Flags: ignoreversion; Components: wxTED
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\wxtedsplash.tti"; DestDir: "{app}"; Flags: ignoreversion; Components: wxTED
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\manual.pdf"; DestDir: "{app}"; Flags: ignoreversion; Components: wxTED
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\sample pages\*"; DestDir: "{app}\samples"; Flags: ignoreversion recursesubdirs createallsubdirs; Components: wxTED
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\Templates\*.tti"; DestDir: "{app}\Templates"; Flags: ignoreversion; Components: wxTED
Source: "E:\dev\wxTED-GitHub\wxted\bin\Release\teletext2.ttf"; DestDir: "{fonts}"; FontInstall: "teletext2"; Flags: onlyifdoesntexist uninsneveruninstall; Components: wxTED

; New Thumbnail Provider files linked to 'thumbnails'
; 'regserver' replaces the need for regsvr32 in your .bat file
Source: "E:\dev\TTIIcon\TTIThumbnailProvider.dll"; DestDir: "{app}"; Flags: ignoreversion regserver restartreplace; Components: thumbnails
Source: "E:\dev\TTIIcon\teletext2.ttf"; DestDir: "{fonts}"; FontInstall: "teletext2"; Flags: onlyifdoesntexist uninsneveruninstall; Components: thumbnails
Source: "E:\dev\TTIIcon\teletext4.ttf"; DestDir: "{fonts}"; FontInstall: "teletext4"; Flags: onlyifdoesntexist uninsneveruninstall; Components: thumbnails

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{group}\Manual"; Filename: "{app}\manual.pdf"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Registry]
; Standard associations (wxTED)
Root: "HKCR"; Subkey: ".tti"; ValueType: string; ValueData: "{#MyAppName}"; Flags: uninsdeletevalue; Components: wxTED
Root: "HKCR"; Subkey: ".ttix"; ValueType: string; ValueData: "{#MyAppName}"; Flags: uninsdeletevalue; Components: wxTED
; ... (rest of the existing registry keys) ...
Root: "HKCR"; Subkey: "{#MyAppName}"; ValueType: string; ValueData: "Program {#MyAppName}"; Flags: uninsdeletevalue; ValueName: ""
Root: "HKCR"; Subkey: "{#MyAppName}\DefaultIcon"; ValueType: string; ValueData: "{app}\{#MyAppExeName},0"; ValueName: ""
Root: "HKCR"; Subkey: "{#MyAppName}\shell\open\command"; ValueType: string; ValueData: """{app}\{#MyAppExeName}"" ""%1"""; ValueName: ""

; Thumbnail Provider Registration (Only if component selected)
; Note: regserver usually handles the COM registration, but some providers 
; require specific ShellEx keys for the .tti extension:
Root: "HKCR"; Subkey: ".tti\ShellEx\{{E357FCCD-A995-4576-B01F-234630154E96}}"; ValueType: string; ValueData: "{{F8A7B9C2-1234-5678-9ABC-DEF012345678}}"; Flags: uninsdeletevalue; Components: thumbnails
